// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "3e26ba59-a983-4866-bce6-02f5e1040bff";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password

void onComandoPainelChange();
void onSistemaAtivoNuvemChange();

String comando_painel;
float som_db_estimado;
float vibracao_mm_s;
bool sistema_ativo_nuvem;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(comando_painel, READWRITE, ON_CHANGE, onComandoPainelChange);
  ArduinoCloud.addProperty(som_db_estimado, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(vibracao_mm_s, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(sistema_ativo_nuvem, READWRITE, ON_CHANGE, onSistemaAtivoNuvemChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
